config/routes.rb
TsentIn::Application.routes.draw do

  devise_for :users

  root :to => 'posts#index'

  resources :posts do
    member do
      post 'favorite' => 'posts#favorite', as: :favorite
    end
  end

  match '/prosfora/:id' => 'posts#show', as: :offer
  match '/prosfores/etiketa/:tag_name' => 'posts#filter', as: :tagged_offers
  match '/prosfores/poli/:city_name' => 'posts#filter', as: :city_offers
  match '/prosfores/poli/:city_name/:tag_name' => 'posts#filter', as: :tagged_city_offers

  match '/logariasmos' => 'user#index', as: :my_account

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :user, :post
  belongs_to :user
  belongs_to :post

  validates :user_id, :uniqueness => {:scope => :post_id}
end

app/models/post.rb
# encoding: UTF-8
class Post < ActiveRecord::Base
  attr_accessible :description, :name, :body, :tag_list, :link, :city_id

  default_scope order('posts.created_at desc')

  validates_presence_of :body, :tag_list, :name
  belongs_to :user
  belongs_to :city

  acts_as_taggable

  has_many :favorites
  has_many :users, through: :favorites, as: :users_favorited


  def city_name
    self.city ? self.city.name : "Σε όλες τις πόλεις"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :post

  def is_favorite? post
    Favorite.exists?(user_id: self.id, post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_tags, :set_cities

  private
    def set_tags
      @tags = Post.tag_counts_on(:tags).order('count  desc', 'name asc')
    end

    def set_cities
      @cities = City.all
      @current_city = City.find_by_name(params[:city_name]) if params[:city_name]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show, :filter ]

  def index
    @posts = Post.all
  end

  def filter
    if params[:city_name] and params[:tag_name]
      @selected_tag = params[:tag_name]
      @posts = Post.where(city_id: @current_city.id).tagged_with(params[:tag_name])
    elsif params[:tag_name]
      @selected_tag = params[:tag_name]
      @posts = Post.tagged_with(params[:tag_name])
    else
      @posts = Post.where(city_id: @current_city.id)
      @tags = @posts.tag_counts_on(:tags).order('count  desc', 'name asc')
    end
    render :index
  end

  def create
    sanitize_properties
    @post = Post.new(params[:post])
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render action: 'new'
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def favorite
    begin
      post = Post.find(params[:id])
      favorites = Favorite.new(user: current_user, post: post)
      if favorites.save!
        @post = Post.find(params[:id])
        render 'posts/favorite'
      end
    rescue Exception
      head :bad_request
    end

  end

  private

  def missing_http? link_url
    !URI.parse(link_url).scheme rescue false
  end

  def sanitize_properties
    params[:post].delete(:city_id)  if params[:post][:city_id].empty?
    params[:post][:tag_list].downcase!
    params[:post][:link] = "http://#{link_from(params)}" if missing_http?(link_from(params))
  end

  def link_from parameters
    params[:post][:link]
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    @posts = Post.limit(5).where(user_id: current_user.id)
    @favorites = current_user.favorite_posts.limit(5)
  end

end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
    #{messages}
    </div>
    HTML
    html.html_safe
  end

  def path_for_all_tags
    @current_city ? city_offers_path(@current_city.name) : root_path
  end

  def all_tags_class
    @selected_tag ? '' : 'active'
  end

  def current_city
    @current_city ? @current_city.name : "Σε όλες τις πόλεις"
  end

  def path_for_tag tag
    @current_city ? tagged_city_offers_path(@current_city.name, tag.name) :  tagged_offers_path(tag.name)
  end

  def class_for_tag tag
    @selected_tag.eql?(tag.name) ? 'active' : ''
  end

  def path_for_city city
    @selected_tag ? tagged_city_offers_path(city.name, @selected_tag.name) :  city_offers_path(@current_tag.name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.haml
.container
  %p ExtractMethod  © copyright 2013 all rights reserved
  %p
    Για σχόλια και εισηγήσεις
    = mail_to "despo@extractmethod.com", "επικοινωνήστε", subject: "Σχετικά με το tsent.in"
    μαζί μας

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "τσεντ.ίν", root_path, :class => 'brand'
%ul.nav.pull-right
  %li.dropdown
    %a{ href: "#", class: "dropdown-toggle", :"data-toggle" => "dropdown"}
      -if user_signed_in?
        =current_user.email
      %b.icon-cog.icon-white
      %b.caret
    %ul.dropdown-menu
      -if user_signed_in?
        %li= link_to "Οι προσφορές μου",  my_account_path
        %li.divider
        %li= link_to "Διαχείρηση λογαριασμού",  edit_user_registration_path
        %li= link_to('Αποσύνδεση', destroy_user_session_path, :method=>'delete')
      - else
        %li= link_to('Συνδεθείτε', new_user_session_path)
        %li.divider
        %li= link_to(t('forgot_password'), new_user_password_path)
        %li= link_to('Δημιουργία λογαριασμού', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "τσεντ.ίν"
    %meta{:content => "Κυπριακή διαδυκτιακή κοινότητα. Προσθέστε τις προσφορές σας ή προσφορές που έχετε δει κάπου και μπορούν να εξυπηρετήσουν το κυπριακό κοινό.", :name => "description"}
    %meta{:content => "ExtractMethod", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    %a{ :href => "https://github.com/despo/tsentin" }
      %img{ :style => "position: absolute; top: 41px; right: 0; border: 0;",
        :src => "https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png",
        :alt => "Fork me on GitHub" }
    %header
      .container
        .row
          .span3.offset2
            =image_tag 'tsentin.png', class: 'img-rounded'

          .span3
            %p.lead
              %h1
                κυπριακές τοπικές προσφορές
                %small γιατί το τσεντίν εφκέρωσεν

    #main{:role => "main"}
      .container
        .content
          .span12
            .row.show-grid
              = render 'layouts/messages'
              .span9
                = yield
              .span3
                = render 'posts/sidebar'
      %footer
        =render 'layouts/footer'

app/views/posts/_favorites.html.haml
.row{ id: "favorite#{post.id}" }
  %small.pull-right
    - active = current_user && current_user.is_favorite?(post) ? 'active' : ''
    =link_to favorite_post_path(post), remote: true, method: :post, class: "favorite #{active}" do
      %i.icon-heart
      =post.favorites.length

app/views/posts/_post.html.haml
.span3
  .post.thumbnail
    .caption.well{ style: 'cursor: pointer' }
      .row.pull-right
        %small=post.city_name
      =link_to offer_path(post) do
        .row
          %h6=post.name
        .row
          %p.body.limit-text
            =post.body
            - if post.body and post.body.length > 180
              ="..."
      =render 'posts/favorites', post: post
    .row
      %small.tags.pull-right
        - post.tags.each do |t|
          %span.label.label-tag
            =link_to t.name, tagged_offers_path(t.name)

app/views/posts/_sidebar.html.haml
- if current_page?(new_post_path)
  =link_to 'Προσθήκη προσφοράς', new_post_path, class: 'btn btn-primary btn-block btn-large disabled'
- else
  =link_to 'Προσθήκη προσφοράς', new_post_path, class: 'btn btn-primary btn-block btn-large'

%br
.btn-toolbar
  .btn-group
    %button.btn.btn-small
      = current_city
    %button.btn.btn-small.dropdown-toggle{ "data-toggle" => "dropdown" }
      %span.caret
    %ul.dropdown-menu{ role: "menu", :"aria-labelledby" => "dropdownMenu" }
      %li=link_to "Σε όλες τις πόλεις", posts_path unless @current_city.nil?
      - @cities.each do |city|
        %li
          =link_to city.name, city_offers_path(city.name)


%ul.nav.nav-tabs.nav-stacked.sidebar
  %li.title Ετικέτες
  %li{ class: all_tags_class }
    =link_to path_for_all_tags do
      'Ολες
      %span.badge.badge-success=@tags.length
  - @tags.each do |tag|
    %li.sidebar-link{ class: class_for_tag(tag) }
      =link_to path_for_tag(tag) do
        =tag.name
        %span.badge.badge-error= tag.count

app/views/posts/favorite.js.erb
$("#favorite<%= @post.id %>").replaceWith("<%= j render('favorites', post: @post) %>");

app/views/posts/index.html.haml
#posts.thumbnails
  = render partial: :post, collection: @posts

app/views/posts/new.html.haml
%legend Προσφορά
= simple_form_for @post, html: { class: 'form-vertical' } do |f|
  = display_base_errors @post

  = f.input :name, :wrapper => :prepend, label: false do
    = content_tag :span, t("post.name"), :class => "add-on"
    = f.input_field :name, placeholder: 'Δωρεάν καφές και γλύκισμα'

  = f.input :body, as: :text, input_html:  { class:  "span6" }, label: t("post.information"), placeholder: 'Στους 10 καφέδες, ένας καφές και ένα κομμάτι γλύκισμα δωρεάν. Μπορείτε να μας βρείτε στη Λεωφόρο Ελλάδος 999. Για περισσότερες πληροφορίες επικοινωνήστε μαζί μας στο 223333333 ', input_html: { rows: 5 }

  = f.input :link, label: t("post.link"), placeholder: 'http://link/to/page', input_html: { rows: 5 }

  = f.input :city_id, label: 'Πόλη', collection: City.all, prompt: "Επιλέξτε πόλη"

  = f.input :tag_list, input_html:  { class:  "span6" }, label: 'Ετικέτες', required: true, placeholder: 'καφές, επιδόρπιο'

  .form-actions
    = f.button 'submit', class: "btn-primary"

app/views/posts/show.html.haml
#post
  .row
    %h3.title
      = @post.name
      %small= @post.city ? @post.city.name : "Σε όλες τις πόλεις"
    .body.well
      =simple_format(@post.body)
      %br
      =link_to @post.link, @post.link
  .row.pull-right
    %small.tags
      - @post.tags.each do |t|
        %span.label.label-tag
          =link_to t.name, tagged_offers_path(t.name)
  .row
    .created_at= "Πρόστέθηκε στις #{l @post.created_at}"

app/views/user/index.html.haml
.row
  %legend Οι τελευταίες προσφορές σας
  - unless @posts
    %p Δεν έχετε προσθέσει προσφορές :(
  - else
    #offers
      = render partial: :post, collection: @posts

.row
  %legend Αγαπημένες προσφορές
  -unless @favorites
    %p Δεν έχετε επιλέξει αγαπημένες προσφορές :(
  - else
    #favorites
      = render partial: :post, collection: @favorites